#!/bin/bash

url=`cat .git/config | grep url | sed "s:.\+url = ::"`

chromestart=$1

if [ -z $url ]
then
    echo URL not found
fi

if [ "$chromestart" == "-b" ] 
then
    start chrome $url
else
    echo $url
fi




