#!/bin/bash

# SUMMARY: execute git-clone without prefix url, that is, only use repository name.

# <MOTIVATION>
# Every git repository url has same prefix string from start to username, 
# so it is waste of time to type all url string. This script make user type
# only repository name for "git clone"
# 
# <EXPECTED OUTCOMES>
# Resuce working hours. 

target=$1

if [ -z "$target" ]
then
    echo No target repository 
    exit 1
fi

echo target repository: $target

checker=`echo $target | sed 's:\([0-9a-zA-Z_\-]\+\):match:'`
gituser="KIMGEONUNG"

if [ "$checker" != "match" ]
then
    echo Fail: Invalid repository format
    exit 1
fi

git clone https://github.com/$gituser/$target
